	$script_apache = <<-SCRIPT
	apt-get update
	apt-get install php
	apt-get -y install apache2
	apt-get -y install puppet
	SCRIPT

	$script_mysql = <<-SCRIPT1
	apt-get update
	apt-get -y install mysql-server
	SCRIPT1
	
	$script_ansible = <<-SCRIPT
	apt-get update
	apt-get -y install software-properties-common
	apt-add-repository --yes --update ppa:ansible/ansible
	apt-get install -y ansible
	SCRIPT
	
	Vagrant.configure("2") do |config|

		config.vm.box = "ubuntu/bionic64"
		config.vm.define "apache" do |apache|

			apache.vm.network "forwarded_port",guest: 80, host: 8081
			apache.vm.network "public_network"
 
			config.vm.synced_folder ".", "/home/vagrant",type:"virtualbox"
			apache.vm.synced_folder ".", "/home/vagrant"
			apache.vm.synced_folder "/Users/Maju/.vagrant.d/boxes/.vagrant", "/home/vagrant"
 

		apache.vm.provision "shell", inline: $script_apache
		apache.vm.provision "shell", inline: "cat /home/vagrant/id_rsa.pub >> .ssh/authorized_keys"


		end
	end
	
	Vagrant.configure("2") do |config|
	
		config.vm.box = "ubuntu/bionic64"
		config.vm.define "mysql" do |mysql|
			mysql.vm.hostname = "mysqldb"
			mysql.vm.network "forwarded_port",guest: 3306, host: 3306
			mysql.vm.network "public_network", ip:"192.168.27.251"

  
		mysql.vm.network "public_network", ip: "192.168.27.251"
		config.vm.synced_folder ".", "/home/vagrant",type:"virtualbox"
		mysql.vm.synced_folder ".", "/home/vagrant"
		mysql.vm.synced_folder "/Users/Maju/.vagrant.d/boxes/.vagrant", "/home/vagrant"
		
		mysql.vm.provision "shell", inline: $script_mysql
		mysql.vm.provision "shell", inline: "cat /home/vagrant/id_rsa.pub >> .ssh/authorized_keys"
	
		end
	end
		


		Vagrant.configure("2") do |config|
			config.vm.box = "ubuntu/bionic64"
			config.vm.define "ansible" do |ansible|

			ansible.vm.hostname = "ansible"
			ansible.vm.network "public_network", ip: "192.168.27.252"

		

			ansible.vm.synced_folder ".", "/home/vagrant"
			ansible.vm.synced_folder "/Users/Maju/.vagrant.d/boxes/.vagrant/machines/mysql/virtualbox", "/vagrant"

			ansible.vm.provision "shell", inline: $script_ansible

			ansible.vm.provision "shell",inline: "cp /vagrant/private_key  /home/vagrant/id_rsa && \
						chmod 600 /home/vagrant/id_rsa && \
						chown vagrant:vagrant /home/vagrant/id_rsa"

			ansible.vm.provision "shell",
			inline: "ansible-playbook -i /home/vagrant/hosts /vagrant/playbook.yml"
		end
	end
	

